# Generated by Django 4.1.6 on 2023-02-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsInformation',
            fields=[
                ('news_title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('news_details', models.TextField(max_length=200)),
                ('cover_image', models.ImageField(default='default.jpg', null=True, upload_to='cover_image')),
            ],
        ),
    ]
